### ISSUE TITLE
Ensure that a processing job's status is always updated correctly

### ISSUE THREAD

**Issue by annavik** [RolnickLab/antenna#721]
## Summary

If something goes wrong with a job, we are seeing an error, but the job status still has the value "STARTED". Sometimes, we have the same problem for successful jobs (job is done, but the status is still "STARTED"). The problem affects the overall status, and also status for individual stages.

## Detailed Description

Not getting the correct status makes it difficult to present correct information to users, for example adjust the status bar color and labels to highlight there is a problem.

### Environment
- OS and/or device: Mac OS
- Browser Chrome
- Version: Production

## Screenshots

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/a1c567d9-8b6f-411e-b91e-77e0de0b8020" />

**Comment by annavik** [comment]
Also a bit related: after doing a retry on the job above (https://antenna.insectai.org/projects/107/jobs/1244), things seem to go better, except the job never changed its status to "SUCCESS" and still looks "STARTED".

**Comment by annavik** [comment]
This job (see https://antenna.insectai.org/projects/107/jobs/1246) also stopped due to problems, but did not had the status updated, so it still looks like it's running:

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/15f19056-a66b-4edc-bda2-a757f1e1b6c6" />

**Comment by mihow** [comment]
This is related to #719

**Comment by mihow** [comment]
This is addresses & fixed by the changes in #910

**Comment by annavik** [comment]
I'm sorry, but I still have the same problems here. From a user perspective I wouldn't consider this as fixed. For example, this job I started this morning looks like it's running but is actually stuck. I have also recently seen jobs that has errors, but I can't understand from the status if still active or not.

<img width="1728" height="1080" alt="Image" src="https://github.com/user-attachments/assets/c430fe6a-65b8-472f-9fc9-ae259bb25a0d" />

Can we keep this issue open until we have tested things a bit more?

**Comment by mihow** [comment]
Sorry this wasn't suppose to be closed. I must have used a keyword in my PR. It will be fixed in https://github.com/RolnickLab/antenna/pull/910

The changes in #937 only affect the _initial_ status being wrong, when the job is first created.

The job status will never be updated once the background task worker disappears, so I believe that's the cause of this issue.

**Comment by annavik** [comment]
Oh I see, that make sense, thanks for reopening!

**Comment by mihow** [comment]
There are likely two reasons why the job status is not being updated:
- The main celery background task for the job is disconnecting & disappearing, so the job status is never updated. I believe the fix for this is the watchdog task approach we are testing in #910. Where a scheduled "check status" task runs periodically to check on a job, or _all_ running jobs. Rather than a single long-running task per job.
- There are concurrency issues with the job logs & status. Some threads may be saving stale data to the job instance in the database. 

Both of these should be addressed. No. 2 may be a smaller change.

**Comment by mihow** [comment]
Plan: implement the watch dog task from #910 so that the job status can be updated even if the original background task disappeared or failed.
